### PR TITLE
Migrate PDFFilter to Spring-AutoConfiguration for CMCC-10

### PR DESCRIPTION
**Pull request by blackappsolutions**
…ently not recognized in cmcc10

* introduced Configuration class and removed old xml beans file
* remove test-ng library, because I could not see any benefit in using it
* Spring-ified PdfCreationFilterTest
* Simplified configuration and processing of match-expression

### CODE REVIEW

**Comment by mgoellnitz** [comment]
This commit introduces 
* a test dependency to the springframework, which was not present before.
* a change in formatting rules with a bunch lines which don't change semantics
As a result I cannot see, where the actual change is, which made a difference to let it work and produce the "I'm there" header. I need some more discussion on this.

**Comment by blackappsolutions** [comment]
So let me guide you through the key points of the implementation:

1. Spring autoconfiguration. The new way to do it in spring-5. And cmcc10 widely adopted this pattern. The Configuration class is declared here:
https://github.com/provocon/coremedia-pdf-filter/blob/1f0c8623694de45d292b1a8783e7af4f79b7cf09/pdf-filter-cae/src/main/resources/META-INF/spring.factories#L1
2. Configuration Class, which is used now in favor of spring xml configuration. Here, the component scan starts
https://github.com/provocon/coremedia-pdf-filter/blob/1f0c8623694de45d292b1a8783e7af4f79b7cf09/pdf-filter-cae/src/main/java/de/provocon/coremedia/cms/view/PdfFilterConfiguration.java#L10
3. Filter is now a @Component and in conjunction with component-scan instanciated
https://github.com/provocon/coremedia-pdf-filter/blob/1f0c8623694de45d292b1a8783e7af4f79b7cf09/pdf-filter-cae/src/main/java/de/provocon/coremedia/cms/view/PdfCreationFilter.java#L40
4. Property replacement is much easier now that way
https://github.com/provocon/coremedia-pdf-filter/blob/1f0c8623694de45d292b1a8783e7af4f79b7cf09/pdf-filter-cae/src/main/java/de/provocon/coremedia/cms/view/PdfCreationFilter.java#L41
https://github.com/provocon/coremedia-pdf-filter/blob/1f0c8623694de45d292b1a8783e7af4f79b7cf09/pdf-filter-cae/src/main/java/de/provocon/coremedia/cms/view/PdfCreationFilter.java#L46

Hope this helps.

**Comment by blackappsolutions** [comment]
What do you mean with that?
> produce the "I'm there" header

**Comment by mgoellnitz** [comment]
"X-PDFFilter: available"

**Pull request merged**
